# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301f8249cf36e2115705666fc799cc8f0a94f2a85ff16fe04acdea6292f9c7280bf155450d72afac43958d79bb6a465e40c20c2d1ce9c90367b88c0abbb6399b

test:
  secret_key_base: 81319c3eda58dc7b64d6af6f732acb4f4d2b05e0cf2de9c9b37af8b82a2af7da05559ed2e0ef2c2a308b9ce8c3e98eb3e4314df7a0259ddc515c5531c82170e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
